### ISSUE TITLE
Opt in directive

### ISSUE THREAD

**Issue by brianchance** [jonsamwell/angular-auto-validate#16]
First off, think the library is awesome, just what I was looking for with error message handling. 

Anyway to provide an opt-in directive instead of automatically handling all ng-submit and ng-model directives? Something like "auto-validate" on the form that handles the submit method and attaches the behavior to all input elements.

Not sure if I can articulate why, seems better to declare what I am using to my fellow developers.

Brian

**Comment by juanchavezlive** [comment]
Hi @jonsamwell. First of all let me tell you congratulations for your excellent work in this library. I've been analyzing many others and yours is by far the best. 

I ask you to please take issue in consideration. 
Nowadays i'm using some inputs without any container with the 'form-group' class (because i don't require the container, the inputs doesn't contain a label for example.).... but in all these cases i get the error: "invalid bs3 form structure elements must be wrapped by a form-group class" each time i type something in them.

Could you please tell me if there is a workaround for this or well if you have in mind integrate this issue inside the directive?

I look forward to hear from you. Best regards

**Comment by jonsamwell** [comment]
@juanchavezlive I think you will need to create a custom dom modifer (how to here http://jonsamwell.github.io/angular-auto-validate/#custom_dom_modifiers).  The default BS3 dom modifier only deals with a default Bootstrap 3 form structure so you could base your new dom modifier off this.  Let me know if you are having a problem with it.

**Comment by jonsamwell** [comment]
@brianchance sorry for the huge delay!!!  This feature is now in (docs to follow).

Add this attribute to the parent form or ng-form to disable the validation of particular forms and the child elements:

```
<form role="form" name="testFrm" novalidate="novalidate"
                  ng-submit="submit();"
                  disable-dynamic-validation>
```
