### ISSUE TITLE
Display validation of groups contained within surrounding element

### ISSUE THREAD

**Issue by michaelryancaputo** [jonsamwell/angular-auto-validate#28]
Hi there, really loving this module. It works great.

I have a feature request. I'm building a form that has a number of repeating elements. To keep the page more readable, i've nested some of the repeating form elements in an accordion panel. This obviously creates issues with the input boxes when they are closed.

I'm wondering if it is possible to add a directive that can tell if any of the input boxes inside that container are invalid, and then possibly add a class to that container so I can add a visual representation of groups of elements that are invalid.

Thanks.

**Comment by jonsamwell** [comment]
I think this would be more of a custom element modifier or a directive rather than part of the actual library itself?  Have a look at the documentation for the custom element modifier and if you need a hand let me know.

http://jonsamwell.github.io/angular-auto-validate/#custom_dom_modifiers

Thanks,
Jon
